### ISSUE TITLE
Regarding exec "i3-sensible-terminal"

### ISSUE THREAD

**Issue by ammgws** [WnndGws/dotfiles#9]
Why do you use `i3-sensible-terminal` [here](https://github.com/WnndGws/dotfiles/blob/5588256d635bfdda5c0de0d471027ef0b54947ba/i3/.config/i3/config#L249) but use `urxvt` explicitly [over here](https://github.com/WnndGws/dotfiles/blob/5588256d635bfdda5c0de0d471027ef0b54947ba/i3/.config/i3/config#L282)? 

Which one should I use (I'm assuming former since seems to be the i3 way?)

**Comment by WnndGws** [comment]
You are correct, i3-sensible-terminal is basically a wrapper script.

The reason i explicitly state urxvt later is because even if i change my $TERMINAL in the future i would still want to use urxvt for these purposes. This is because it is light weight, and allows me to easily set the class to make window management easy. Thus instead of having to change the syntax should i change TERMINAL, i can just leave it as is

**Comment by ammgws** [comment]
Try running urxvt as a daemon process to make it even more faster/responsive.
See [here](https://github.com/ammgws/dotfiles/blob/6820b65034c2f49958d9d011d5963af6c5be8677/X11/xinitrc#L43)
